name: apps
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
   sdk: flutter
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.2.2
  fl_chart: ^0.68.0
  http: ^1.2.2
  get: ^4.6.6
  flutter_launcher_icons: ^0.13.1
  circular_reveal_animation: ^2.0.1
  firebase_core: ^3.5.0
  firebase_auth: ^5.3.0
  qr_flutter: ^4.1.0
  permission_handler: ^11.3.1
  camera: ^0.10.0

flutter_launcher_icons:
 android: "launcher_icons"
 ios: true
 image_path: "assets/images/mbrblue.png"
 min_sdk_android: 21
 cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
